linters:
  LineLength:
    max: 120

  CommentControlStatement:
    enabled: true

  TrailingBlankLines:
    enabled: true

exclude:
  - 'vendor/**/*'
  - 'node_modules/**/*'
  - 'bin/**/*'
  - 'db/schema.rb'
  - 'db/migrate/**/*'
